config/routes.rb
# Locomotive::Application.routes.draw do |map|
Rails.application.routes.draw do

  # admin authentication
  devise_for :admin, :class_name => 'Account', :controllers => { :sessions => 'admin/sessions', :passwords => 'admin/passwords' }

  as :admin do
    get '/admin' => 'admin/sessions#new'
  end

  # admin interface for each website
  namespace 'admin' do
    root :to => 'sessions#new'

    resources :pages do
      put :sort, :on => :member
      get :get_path, :on => :collection
    end

    resources :snippets

    resources :sites

    resource :current_site

    resources :accounts

    resource :my_account

    resources :memberships

    resources :theme_assets do
      get :all, :action => 'index', :on => :collection, :defaults => { :all => true }
    end

    resources :asset_collections

    resources :assets, :path => 'asset_collections/:collection_id/assets'

    resources :images

    resources :content_types

    resources :contents, :path => 'content_types/:slug/contents' do
      put :sort, :on => :collection
    end

    resources :api_contents, :path => 'api/:slug/contents', :controller => 'api_contents', :only => [:create]

    resources :custom_fields, :path => 'custom/:parent/:slug/fields'

    resources :cross_domain_sessions, :only => [:new, :create]

    resource :import, :only => [:new, :show, :create]

    # installation guide
    match '/installation' => 'installation#show', :defaults => { :step => 1 }, :as => :installation
    match '/installation/:step' => 'installation#show', :as => :installation_step

  end

  # sitemap
  match '/sitemap.xml' => 'admin/sitemaps#show', :format => 'xml'

  # magic urls
  match '/' => 'admin/rendering#show'
  match '*path/edit' => 'admin/rendering#show', :defaults => { :editing => true }
  match '*path' => 'admin/rendering#show'
end

app/views/admin/pages/_editable_elements.html.haml
- grouped_editable_elements = @page.editable_elements_grouped_by_blocks

= semantic_fields_for(@page) do |f|
  - unless grouped_editable_elements.empty?
    #editable-elements
      .nav
        - grouped_editable_elements.keys.each_with_index do |name, index|
          = link_to content_tag(:span, name.try(:humanize) || t('admin.pages.form.default_block')), "#block-#{index}", :id => "block-nav-#{index}", :class => "#{'on' if index == 0}"
        .clear

      .wrapper
        %ul{ :id => "blocks" }
          - grouped_editable_elements.keys.each_with_index do |name, index|
            - elements = grouped_editable_elements[name]
            %li{ :id => "block-#{index}", :class => 'block', :style => "display: #{index == 0 ? 'block' : 'none' }" }
              %fieldset.inputs
                %ol
                  - elements.each_with_index do |el, index|
                    = f.fields_for 'editable_elements', el, :child_index => el._index do |g|
                      - case el
                        - when EditableLongText
                          = g.input :content, :label => el.slug.humanize, :hint => el.hint, :as => :text, :input_html => { :class => 'html' }
                        - when EditableShortText
                          = g.input :content, :label => el.slug.humanize, :hint => el.hint
                        - when EditableFile
                          = g.custom_input :source, :label => el.slug.humanize, :hint => el.hint, :css => 'file' do
                            = g.file_field :source
                            - if el.source?
                              %p.remove
                                %strong
                                  = link_to File.basename(el.source.url), el.source.url
                                %span
                                  &nbsp;/&nbsp;
                                  != t('admin.pages.form.delete_file')
                                  = g.check_box :remove_source

app/views/admin/pages/_form.html.haml
- content_for :head do
  = include_javascripts :image_picker, :edit_page
  = include_stylesheets :editable_elements, :fancybox

= f.foldable_inputs :name => :information do

  = f.input :title

  - if not @page.index? and not @page.not_found?
    = f.input :parent_id, :as => :select, :collection => parent_pages_options, :include_blank => false

  = f.input :slug, :required => false, :hint => @page.slug.blank? ? '&nbsp;' : page_url(@page), :input_html => { :data_url => get_path_admin_pages_url, :disabled => @page.index? || @page.not_found? }, :wrapper_html => { :style => "#{'display: none' if @page.templatized?}; height: 50px" }

= f.foldable_inputs :name => :meta do

  = f.input :meta_keywords
  = f.input :meta_description

= f.foldable_inputs :name => :advanced_options do

  = f.input :content_type_id, :as => :select, :collection => current_site.content_types.all.to_a, :include_blank => false, :wrapper_html => { :style => "#{'display: none' unless @page.templatized?}; height: 50px" }

  = f.custom_input :templatized, :css => 'toggle', :style => "#{'display: none' if @page.redirect?}" do
    = f.check_box :templatized

  = f.custom_input :published, :css => 'toggle' do
    = f.check_box :published

  = f.custom_input :listed, :css => 'toggle' do
    = f.check_box :listed

  = f.custom_input :redirect, :css => 'toggle', :style => "#{'display: none' if @page.templatized?}" do
    = f.check_box :redirect

  = f.input :cache_strategy, :as => :select, :collection => options_for_page_cache_strategy, :include_blank => false, :wrapper_html => { :style => "#{'display: none' if @page.redirect?}" }

  = f.input :redirect_url, :required => true, :wrapper_html => { :style => "#{'display: none' unless @page.redirect?}" }

= render 'editable_elements', :page => @page

= f.foldable_inputs :name => :raw_template do
  = f.custom_input :value, :css => 'code full', :with_label => false do
    = f.label :raw_template
    %code{ :class => 'html' }
      = f.text_area :raw_template
    = f.errors_on :template
    .more
      = link_to t('admin.image_picker.link'), admin_theme_assets_path, :id => 'image-picker-link'

app/views/admin/pages/_page.html.haml
%li{ :id => "item-#{page.id}", :class => "#{'not-found' if page.not_found? } #{'templatized' if page.templatized?}"}
  - with_children = !page.children.empty?

  - if not page.index? and with_children
    = image_tag 'admin/list/icons/node_closed.png', :class => 'toggler'
  %em
  %strong= link_to truncate(page.title, :length => 80), edit_admin_page_url(page)

  .more
    %span!= t('.updated_at')
    = l page.updated_at, :format => :short

    - if not page.index? and not page.not_found?
      = link_to image_tag('admin/list/icons/trash.png'), admin_page_url(page), :class => 'remove', :confirm => t('admin.messages.confirm'), :method => :delete

  - if with_children
    %ul{ :id => "folder-#{page._id}", :class => "folder depth-#{(page.depth || 0) + 1}", :data_url => sort_admin_page_url(page), :style => "display: #{cookies["folder-#{page._id}"] || 'block'}" }
      = render page.children

app/views/admin/pages/edit.html.haml
- title link_to(@page.title.blank? ? @page.title_was : @page.title, '#', :rel => 'page_title', :title => t('.ask_for_title'), :class => 'editable')

- content_for :submenu do
  = render 'admin/shared/menu/contents'
  
- content_for :actions do
  = render 'admin/shared/actions/contents'

- content_for :buttons do
  = admin_button_tag :show, "/#{@page.fullpath}", :class => 'show'

%p!= t('.help')

= semantic_form_for @page, :url => admin_page_url(@page), :html => { :class => 'save-with-shortcut', :multipart => true } do |form|

  = render 'form', :f => form

  = render 'admin/shared/form_actions', :back_url => admin_pages_url, :button_label => :update

app/views/admin/pages/index.html.haml
- title t('.title')

- content_for :head do
  = include_javascripts :pages

- content_for :submenu do
  = render 'admin/shared/menu/contents'
  
- content_for :actions do
  = render 'admin/shared/actions/contents'

- content_for :buttons do
  = admin_button_tag :new, new_admin_page_url, :class => 'new'

%p!= t('.help')

- if @pages.empty?
  %p.no-items!= t('.no_items', :url => new_admin_page_url)
- else
  %ul#pages-list
    = render @pages

app/views/admin/pages/new.html.haml
- title t('.title')

- content_for :submenu do
  = render 'admin/shared/menu/contents'
  
- content_for :actions do
  = render 'admin/shared/actions/contents'

%p!= t('.help')

= semantic_form_for @page, :url => admin_pages_url do |form|

  = render 'form', :f => form

  = render 'admin/shared/form_actions', :back_url => admin_pages_url, :button_label => :create