config/routes.rb
# Locomotive::Application.routes.draw do |map|
Rails.application.routes.draw do

  # admin authentication
  devise_for :admin, :class_name => 'Account', :controllers => { :sessions => 'admin/sessions', :passwords => 'admin/passwords' }

  as :admin do
    get '/admin' => 'admin/sessions#new'
  end

  # admin interface for each website
  namespace 'admin' do
    root :to => 'sessions#new'

    resources :pages do
      put :sort, :on => :member
      get :get_path, :on => :collection
    end

    resources :snippets

    resources :sites

    resource :current_site

    resources :accounts

    resource :my_account

    resources :memberships

    resources :theme_assets do
      get :all, :action => 'index', :on => :collection, :defaults => { :all => true }
    end

    resources :asset_collections

    resources :assets, :path => 'asset_collections/:collection_id/assets'

    resources :images

    resources :content_types

    resources :contents, :path => 'content_types/:slug/contents' do
      put :sort, :on => :collection
    end

    resources :api_contents, :path => 'api/:slug/contents', :controller => 'api_contents', :only => [:create]

    resources :custom_fields, :path => 'custom/:parent/:slug/fields'

    resources :cross_domain_sessions, :only => [:new, :create]

    resource :import, :only => [:new, :show, :create]

    # installation guide
    match '/installation' => 'installation#show', :defaults => { :step => 1 }, :as => :installation
    match '/installation/:step' => 'installation#show', :as => :installation_step

  end

  # sitemap
  match '/sitemap.xml' => 'admin/sitemaps#show', :format => 'xml'

  # magic urls
  match '/' => 'admin/rendering#show'
  match '*path/edit' => 'admin/rendering#show', :defaults => { :editing => true }
  match '*path' => 'admin/rendering#show'
end

app/models/extensions/shared/seo.rb
module Extensions
  module Shared
    module Seo
      extend ActiveSupport::Concern

      included do
        field :meta_keywords, :type => String
        field :meta_description, :type => String
      end
      
    end # Seo
  end # Shared
end # Extensions

app/views/admin/shared/menu/_assets.html.haml
- @asset_collections.each do |c|
  %li
    = link_to content_tag(:span, truncate(c.name, :length => 20)), edit_admin_asset_collection_url(c), :class => "#{'on' if @asset_collection.id == c.id}"

app/views/admin/shared/menu/_contents.html.haml
= admin_submenu_item 'pages', admin_pages_url do
  .header
    %p= link_to t('admin.pages.index.new'), new_admin_page_url
  .inner
    %h2!= t('admin.pages.index.lastest_items')
    %ul
      - current_site.pages.latest_updated.minimal_attributes.each do |page|
        %li
          = link_to truncate(page.title, :length => 25), edit_admin_page_url(page)
          %span= time_ago_in_words(page.updated_at)

- each_content_type_menu_item do |content_type|
  .header
    %p= link_to t('admin.contents.index.new'), new_admin_content_url(content_type.slug)
  .inner
    %h2!= t('admin.contents.index.lastest_items')
    %ul
      - content_type.latest_updated_contents.each do |content|
        %li
          = link_to truncate(content.send(content_type.highlighted_field_name).to_s, :length => 20), edit_admin_content_path(content_type.slug, content)
          %span= time_ago_in_words(content.updated_at)

- other_content_types do |content_types|
  .inner
    %ul.big-links
      - content_types.each do |content_type|
        %li
          = link_to truncate(content_type.name, :length => 20), admin_contents_url(content_type.slug)

app/views/admin/shared/menu/_settings.html.haml
= admin_submenu_item 'site', edit_admin_current_site_url
/ = admin_submenu_item 'snippets', admin_snippets_url
= admin_submenu_item 'theme_assets', admin_theme_assets_url
= admin_submenu_item 'account', edit_admin_my_account_url